> # **[Exercise Link](https://www.kaggle.com/code/shahiismyname/exercise-indexing-selecting-assigning/edit)**

In [53]:
import pandas as pd

> # **Loading the dataset**

In [54]:
reviews = pd.read_csv(r"D:\Jupyter Notebook\Datasets\winemag-data-130k-v2.csv", index_col=0)

reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

# **Exercise - 1**

In [55]:
desc = reviews['description']

desc.to_frame()

                                              description
0       Aromas include tropical fruit, broom, brimston...
1       This is ripe and fruity, a wine that is smooth...
2       Tart and snappy, the flavors of lime flesh and...
3       Pineapple rind, lemon pith and orange blossom ...
4       Much like the regular bottling from 2012, this...
...                                                   ...
129966  Notes of honeysuckle and cantaloupe sweeten th...
129967  Citation is given as much as a decade of bottl...
129968  Well-drained gravel soil gives this wine its c...
129969  A dry style of Pinot Gris, this is crisp with ...
129970  Big, rich and off-dry, this is powered by inte...

[129971 rows x 1 columns]

# **Exercise - 2**

> Note that while this is the preferred way to obtain the entry in the DataFrame, many other options will return a valid result, such as reviews.description.loc[0], reviews.description[0], and more!

In [56]:
first_description = reviews.description.iloc[0]

first_description

"Aromas include tropical fruit, broom, brimstone and dried herb. The palate isn't overly expressive, offering unripened apple, citrus and dried sage alongside brisk acidity."

# **Exercise - 3**

> ***reviews.iloc[0 : 1]*** returns only a single row in ***DataFrame***, but if the question is asked to return a single row then it's implicitly asking for ***Series*** not a ***DataFrame***. To return a ***Series***, this line of code is needed ***reviews.iloc[0]***.

In [57]:
first_row = reviews.iloc[0]
first_row

country                                                              Italy
description              Aromas include tropical fruit, broom, brimston...
designation                                                   Vulkà Bianco
points                                                                  87
price                                                                  NaN
province                                                 Sicily & Sardinia
region_1                                                              Etna
region_2                                                               NaN
taster_name                                                  Kerin O’Keefe
taster_twitter_handle                                         @kerinokeefe
title                                    Nicosia 2013 Vulkà Bianco  (Etna)
variety                                                        White Blend
winery                                                             Nicosia
Name: 0, dtype: object

# **Exercise - 4**

In [58]:
first_descriptions = reviews.description.head(10)

first_description

"Aromas include tropical fruit, broom, brimstone and dried herb. The palate isn't overly expressive, offering unripened apple, citrus and dried sage alongside brisk acidity."

# **Exercise - 5**

In [65]:
sample_reviews = reviews.iloc[[1, 2, 3, 5, 8]]

sample_reviews

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem
8,Germany,Savory dried thyme notes accent sunnier flavor...,Shine,87,12.0,Rheinhessen,NaN,NaN,Anna Lee C. Iijima,NaN,Heinz Eifel 2013 Shine Gewürztraminer (Rheinhe...,Gewürztraminer,Heinz Eifel

# **Exercise - 6**

In [74]:
df = reviews.loc[[0, 1, 10, 100] , ['country', 'province', 'region_1', 'region_2']]
df

      country           province      region_1      region_2
0       Italy  Sicily & Sardinia          Etna           NaN
1    Portugal              Douro           NaN           NaN
10         US         California   Napa Valley          Napa
100        US           New York  Finger Lakes  Finger Lakes

# **Exercise - 7**

In [78]:
df = reviews.loc[0: 99 , ['country', 'variety']]

df

     country                   variety
0      Italy               White Blend
1   Portugal            Portuguese Red
2         US                Pinot Gris
3         US                  Riesling
4         US                Pinot Noir
..       ...                       ...
95    France                     Gamay
96    France                     Gamay
97        US                  Riesling
98     Italy                Sangiovese
99        US  Bordeaux-style Red Blend

[100 rows x 2 columns]

# **Exercise - 8**

In [83]:
italian_wines = reviews[reviews.country == 'Italy']

italian_wines.head(2)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo

# **Exercise - 9**

In [ ]:
top_oceania_wines = reviews[(reviews.points >= 95) & (reviews.country.isin(['Australia', 'New Zealand']))]

top_oceania_wines.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
345,Australia,This wine contains some material over 100 year...,Rare,100,350.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Rare Muscat (Ru...,Muscat,Chambers Rosewood Vineyards
346,Australia,"This deep brown wine smells like a damp, mossy...",Rare,98,350.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Rare Muscadelle...,Muscadelle,Chambers Rosewood Vineyards
348,Australia,Deep mahogany. Dried fig and black tea on the ...,Grand,97,100.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Grand Muscat (R...,Muscat,Chambers Rosewood Vineyards
349,Australia,"RunRig is always complex, and the 2012 doesn't...",RunRig,97,225.0,South Australia,Barossa,NaN,Joe Czerwinski,@JoeCz,Torbreck 2012 RunRig Shiraz-Viognier (Barossa),Shiraz-Viognier,Torbreck
356,Australia,"Dusty, firm, powerful: just a few apt descript...",Georgia's Paddock,95,85.0,Victoria,Heathcote,NaN,Joe Czerwinski,@JoeCz,Jasper Hill 2013 Georgia's Paddock Shiraz (Hea...,Shiraz,Jasper Hill